name: Docker Image CI

on:
  push:
    branches: [ "mattia" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the BackEnd Docker image
      run: docker build . --file ChargeMe.BackEnd/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the FrontEnd Docker image
      run: docker build . --file chargeme.frontend/Dockerfile --tag my-image-name:$(date +%s)